from . import chess_com
from . import deezer
from . import duolingo
from . import github
from . import gravatar
from . import imgur
from . import instagram
from . import pinterest
from . import pornhub
from . import spotify
from . import strava
from . import twitter
