from .specific import chess_com
from .specific import deezer
from .specific import duolingo
from .specific import github
from .specific import gravatar
from .specific import imgur
from .specific import instagram
from .specific import pinterest
from .specific import pornhub
from .specific import spotify
from .specific import strava
from .specific import twitter
from . import holehe_
